/**
 * About settings – author info, links, and disclaimer
 *
 * This page gives human context for the app: who created it, where the
 * source code lives, and a clear note that parts of the code were
 * assisted by AI. It uses the same glass styling as other settings pages.
 */

import authorLogo from '../../assets/author/authorlogo.png';

export function AboutSettings() {
  return (
    <div className="glass-panel" style={{ padding: 24, maxWidth: 720 }}>
      <h1>About FinPoster</h1>

      <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 4, marginBottom: 20 }}>
        Version: V.0.1.0.0-alpha
      </p>

      <section style={{ marginBottom: 24 }}>
        <h2>People</h2>
        <div style={{ display: 'flex', gap: 16, alignItems: 'center', marginTop: 12 }}>
          <img
            src={authorLogo}
            alt="Author"
            style={{
              width: 72,
              height: 72,
              borderRadius: '50%',
              objectFit: 'cover',
              boxShadow: '0 0 24px rgba(0,0,0,0.6)',
            }}
          />
          <div>
            <h3 style={{ margin: 0, fontSize: '1.05rem' }}>Author – binarygeek119</h3>
            <p style={{ margin: '4px 0', color: 'var(--text-secondary)' }}>
              Created the concept and direction for FinPoster as a Jellyfin‑inspired
              digital signage and poster display system.
            </p>
            <p style={{ margin: 0, fontSize: 14, color: 'var(--text-muted)' }}>
              Focused on clean, cinematic visuals and a glass-style dashboard feel.
            </p>
          </div>
        </div>
      </section>

      <section style={{ marginBottom: 24 }}>
        <h2>Source code</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: 8 }}>
          The full project source is available on GitHub:
        </p>
        <a
          href="https://github.com/binarygeek119/FinPoster"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 8,
            padding: '8px 12px',
            borderRadius: 8,
            border: '1px solid var(--glass-border)',
            background: 'rgba(0,0,0,0.3)',
          }}
        >
          <span style={{ fontWeight: 500 }}>github.com/binarygeek119/FinPoster</span>
        </a>
      </section>

      <section style={{ marginBottom: 24 }}>
        <h2>What the display needs</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: 8 }}>
          The poster display reads the browser viewport size (window width and height) to scale
          the layout so it fills the screen. Resizing the window updates the scale automatically.
          No special resolution is required; any window or full-screen size works.
        </p>
        <p style={{ color: 'var(--text-muted)', fontSize: 14 }}>
          The design is fixed at 1440×900 and scaled to cover the viewport. Viewport dimensions
          are available app-wide via the <code style={{ fontSize: 12 }}>useViewport()</code> hook
          for any component that needs them.
        </p>
      </section>

      <section>
        <h2>AI-coded disclaimer</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: 8 }}>
          This entire application was coded with the help of an AI coding assistant.
        </p>
        <p style={{ color: 'var(--text-muted)', fontSize: 14 }}>
          The overall design, structure, and implementation were generated by AI based on the
          author&apos;s requirements and guidance. The author reviewed the behavior to make
          sure it matches the intended experience, but the code itself should be treated as
          AI-generated and may evolve over time.
        </p>
      </section>
    </div>
  );
}

